#!/usr/bin/env node

const fs = require('fs').promises;
const path = require('path');

// Function to read sync state
async function readSyncState() {
    try {
        const statePath = path.join(__dirname, 'sync-state.json');
        const stateContent = await fs.readFile(statePath, 'utf8');
        return JSON.parse(stateContent);
    } catch (error) {
        console.log('No sync state found, starting fresh');
        return { lastProcessedTimestamp: 0, lastProcessedMessageId: null, processedFiles: [], version: "1.0" };
    }
}

// Function to update sync state
async function updateSyncState(newState) {
    const statePath = path.join(__dirname, 'sync-state.json');
    await fs.writeFile(statePath, JSON.stringify(newState, null, 2));
    console.log('Sync state updated successfully');
}

// Function to ensure directory exists
async function ensureDirectoryExists(dirPath) {
    try {
        await fs.access(dirPath);
    } catch (error) {
        if (error.code === 'ENOENT') {
            await fs.mkdir(dirPath, { recursive: true });
        } else {
            throw error;
        }
    }
}

// Main sync function
async function runSync() {
    try {
        console.log('Starting Second Brain sync process...');
        
        // Read current sync state
        const syncState = await readSyncState();
        console.log('Current sync state:', syncState);
        
        // Get current timestamp
        const currentTimestamp = Date.now();
        
        // Create log filename with precise timestamp
        const date = new Date();
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        const hours = String(date.getHours()).padStart(2, '0');
        const minutes = String(date.getMinutes()).padStart(2, '0');
        const seconds = String(date.getSeconds()).padStart(2, '0');
        const logFilename = `${year}-${month}-${day}-${hours}-${minutes}-${seconds}`;
        
        // Ensure logs directory exists
        const logsDir = path.join(__dirname, 'content', 'logs');
        await ensureDirectoryExists(logsDir);
        
        // Create log content with proper frontmatter
        const logContent = `---\ndate: ${logFilename}\ntype: sync-log\nsummary: "Automated sync task execution at ${logFilename}"\ntopics:\n  - second-brain\n  - automation\n  - system-maintenance\nai_generated: true\n---\n\n# ${logFilename}\n\n## Sync Task Execution\n\n- **Timestamp**: ${new Date().toISOString()}\n- **Previous State**: lastProcessedTimestamp=${syncState.lastProcessedTimestamp}\n- **Action**: Cron job executed successfully\n- **Status**: Ready for conversation processing\n\n> This log was automatically generated by the Second Brain sync system.\n`;
        
        // Write log file
        const logFilePath = path.join(logsDir, `${logFilename}.md`);
        await fs.writeFile(logFilePath, logContent);
        console.log(`Log file created: ${logFilePath}`);
        
        // Update sync state with current timestamp
        const newSyncState = {
            lastProcessedTimestamp: currentTimestamp,
            lastProcessedMessageId: `sync-${logFilename}`,
            processedFiles: [...syncState.processedFiles, logFilename],
            version: "1.0"
        };
        
        await updateSyncState(newSyncState);
        
        console.log('Second Brain sync completed successfully!');
        return true;
        
    } catch (error) {
        console.error('Error during sync process:', error);
        return false;
    }
}

// Run the sync
if (require.main === module) {
    runSync().then(success => {
        process.exit(success ? 0 : 1);
    });
}